name: "beam_stretch"
description: "0.1m cubes are compressed by 0.05m/s for 1 second, then are held compressed for 1 second"

# Print rate
print-interval: 3.33e-4

# Output folder
output-folder: "../output/beam_stretch"

# Beam stretch simulation specific
stretch-velocity: 0.05 # m/s
stretch-time: 1 # s

# acceleration due to gravity
g-accel: 9.81 # m/s2

# type of simulation to run
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"

# time-step: 3.33e-3
time-step: 3.33e-5
end-time: 10
objects:
  -
    name: "Cube1"
    # type: "XPBDMeshObject"
    type: "FirstOrderXPBDMeshObject"
    # filename: "../resource/cube/cube8.msh"
    filename: "../resource/tissue/tissue_block1x1x0.1_2subdiv.msh"
    # filename: "../resource/tissue/tissue_block1x1x0.1_1subdiv.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.1
    position: [0, 0, 0.005]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0.00000
    damping-multiplier: 12 #0.1 #2000000
    residual-policy: "Every-Substep" #"Every-Substep"
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    # solve-mode: "Simultaneous"
    # solve-mode: "Simultaneous-Constant-B"
    solve-mode: "Simultaneous-Smallest-Edge-B"
    # solve-mode: "Sequential-Init-Lambda"

  # -
  #   name: "Cube2"
  #   type: "XPBDMeshObject"
  #   filename: "../resource/tissue/tissue_block1x1x0.1_2subdiv.msh"
  #   material:
  #     name: "Soft Tissue"
  #     density: 1000
  #     E: 6e4
  #     nu: 0.49
  #   color: [1.0, 0.0, 0.0, 1.0]
  #   draw-points: false
  #   draw-edges: true
  #   max-size: 0.1
  #   position: [0, 0.15, 0.005]
  #   velocity: [0, 0, 0]
  #   rotation: [0, 0, 0]
  #   num-solver-iters: 1
  #   damping-stiffness: 0.00001
  #   residual-policy: "Every-Substep"
  #   # solve-mode: "Split-Deviatoric-Sequential"
  #   # solve-mode: "Split-Deviatoric-Simultaneous9"
  #   # solve-mode: "Split-Deviatoric-Simultaneous10"
  #   solve-mode: "Sequential"
  #   # solve-mode: "Simultaneous"
  #   # solve-mode: "Sequential-Init-Lambda"
  
  # -
  #   name: "Ground"
  #   type: "RigidMeshObject"
  #   primitive-type: "Plane"
  #   size: [0.15, 0.3, 0]
  #   position: [0, 0.1, 0]
  #   color: [1.0, 1.0, 1.0, 1.0]


