name: "beam_stretch"
description: "0.1m cubes are compressed by 0.05m/s for 1 second, then are held compressed for 1 second"

# Beam stretch simulation specific
stretch-velocity: -0.05 # m/s
stretch-time: 1 # s

# acceleration due to gravity
g-accel: 9.81 # m/s2

# type of simulation to run
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"

time-step: 2.5e-4
end-time: 2
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    filename: "../resource/beam/cube16.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 0.1
    position: [0, 0, 1]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    # solve-mode: "Simultaneous"
    # solve-mode: "Sequential-Init-Lambda"

  -
    name: "Cube2"
    type: "XPBDMeshObject"
    filename: "../resource/beam/cube16.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.49
    color: [1.0, 0.0, 0.0, 1.0]
    draw-points: false
    max-size: 0.1
    position: [0, 0, 0.85]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    solve-mode: "Simultaneous"
    # solve-mode: "Sequential-Init-Lambda"
  
  # -
  #   name: "Ground"
  #   type: "RigidMeshObject"
  #   primitive-type: "Plane"
  #   size: [0.1, 0.5, 0]
  #   position: [0, 0, 0]
  #   color: [1.0, 1.0, 1.0, 1.0]


