name: sim-gpu
services:
  dev:
    privileged: true
    tty: true
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    environment:
      DISPLAY: ${DISPLAY}
      LD_LIBRARY_PATH: "/usr/local/lib"
    volumes:
      - "./:/workspace"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
