name: sim-cpu
services:
  dev:
    privileged: true
    tty: true
    build:
      context: "./"
      dockerfile: "./Dockerfile.CPU"
    environment:
      DISPLAY: ${DISPLAY}
      LD_LIBRARY_PATH: "/usr/local/lib"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - "./:/workspace"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics, display]

