name: sim-ros
services:
  dev:
    privileged: true
    tty: true
    build:
      context: "./"
      dockerfile: "./Dockerfile.ROS"
    environment:
      DISPLAY: ${DISPLAY}
      LD_LIBRARY_PATH: "/usr/local/lib"
    volumes:
      - "./:/workspace"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: "host"
    
