name: "static_loading"
description: ""

# Print rate
print-interval: 3e-4

# Output folder
output-folder: "../output/static_loading"

# acceleration due to gravity
g-accel: 9.81 # m/s2

# type of simulation to run
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"

time-step: 1e-5
end-time: 10
objects:
  -
    name: "FirstOrderCube1"
    # type: "XPBDMeshObject"
    type: "FirstOrderXPBDMeshObject"
    filename: "../resource/tissue/tissue_block1x1x0.1_4subdiv.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e5
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 0.1 #1
    position: [0, 0, 10]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-multiplier: 0.01 #10000000 #0.001 #2
    residual-policy: "Every-Substep"
    # solve-mode: "Sequential"
    # solve-mode: "Simultaneous"
    solve-mode: "Simultaneous-Constant-B"
    # solve-mode: "Simultaneous-Jacobi"
    # solve-mode: "Simultaneous-Convergent-Jacobi"



