name: "TissueGrasping"
g-accel: 9.81 # m/s2
sim-mode: "Visualization"
time-step: 1e-5
end-time: 10
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    filename: "../resource/1x1x0.25_tissueblock4-2.obj"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.4999
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 0.1
    position: [0, 0, 0.025]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    solve-mode: "Simultaneous"

  - 
    # name: "Cube2"
    # type: "XPBDMeshObject"
    # filename: "../resource/refined_cube.msh"
    # material:
    #   name: "Rubber"
    #   density: 1000
    #   E: 3e6
    #   nu: 0.49
    # color: [1.0, 0.0, 0.0, 1.0]
    # draw-points: false
    # max-size: 5
    # position: [0, 5, 10]
    # velocity: [0, 0, 0]
    # rotation: [0, 30, 0]
    # num-solver-iters: 1
    # damping-stiffness: 100000
    # solve-mode: "Sequential"
  
  -
    name: "Ground"
    type: "RigidMeshObject"
    primitive-type: "Plane"
    size: [0.2, 0.2, 0]
    position: [0, 0, 0]
    color: [1.0, 1.0, 1.0, 1.0]


