name: "Virtuoso Trachea"

# Tissue grasping simulation-specific parameters
input-device: "Keyboard" # the input device for interactivity - "Mouse" or "Haptic" (Phantom Omni)
fixed-faces-filename: "../resource/tissue/tracheal_tumor_v2_fixed_faces.txt"

g-accel: 0 # m/s2
sim-mode: "Visualization"
# sim-mode: "Frame-by-frame"
# sim-mode: "AFAP"
time-step: 3.33e-3 # for FO XPBD
# time-step: 3.33e-5 # for normal XPBD
collision-rate: 33333
fps: 30
end-time: 1000
objects:

  -
    name: "Arm1"
    type: "VirtuosoArm"
    outer-tube-diameter: 1.56e-3
    outer-tube-radius-of-curvature: 1.5383e-2
    outer-tube-distal-straight-length: 5e-3
    outer-tube-translation: 6e-3
    outer-tube-rotation: 0
    inner-tube-diameter: 1.04e-3
    inner-tube-translation: 2.3e-2
    outer-tube-position: [0, -0.03, 0]
    collisions: false
  # -
  #   name: "Arm1"
  #   type: "VirtuosoArm"
  #   outer-tube-diameter: 1.5e-2
  #   outer-tube-curvature: 1e-1
  #   outer-tube-translation: 1e-2
  #   outer-tube-rotation: 45
  #   inner-tube-diameter: 1e-2
  #   inner-tube-translation: 2e-3
  #   outer-tube-position: [0, -0.03, 0]
  #   collisions: true

  -
    name: "Cube1"
    # type: "XPBDMeshObject"
    type: "FirstOrderXPBDMeshObject"
    filename: "../resource/tissue/tracheal_tumor_v2.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.49
    color: [1.0, 0.0, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.06
    position: [0, 0, 0]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    residual-policy: "Never"
    solver-type: "Gauss-Seidel"
    constraint-type: "Stable-Neohookean-Combined"
    with-residual: false
    with-damping: false
    damping-multiplier: 400000000
    collisions: false

  # -
  #   name: "sphere"
  #   type: "RigidSphere"
  #   radius: 1e-3
  #   density: 1000000
  #   position: [0, -0.01, 0.005]
  #   velocity: [0, 0.1, 0]
  #   fixed: false
  #   collisions: true

  - 
    # name: "Cube2"
    # type: "XPBDMeshObject"
    # filename: "../resource/refined_cube.msh"
    # material:
    #   name: "Rubber"
    #   density: 1000
    #   E: 3e6
    #   nu: 0.49
    # color: [1.0, 0.0, 0.0, 1.0]
    # draw-points: false
    # max-size: 5
    # position: [0, 5, 10]
    # velocity: [0, 0, 0]
    # rotation: [0, 30, 0]
    # num-solver-iters: 1
    # damping-stiffness: 100000
    # solve-mode: "Sequential"


