name: "blah"
g-accel: 0 # m/s2
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"
time-step: 1e-3
fps: 30
end-time: 5
objects:
  -
    name: "Cube1"
    # type: "FirstOrderXPBDMeshObject"
    type: "XPBDMeshObject"
    # type: "FastFEMMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/tissue/Prostate.msh"
    # filename: "../resource/tissue/Trachea_processed.stl"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.4
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.5
    position: [-0.25, 0, 10]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    collisions: false
    damping-multiplier: 20000
    solver-type: "Gauss-Seidel"
    # solver-type: "Jacobi"
    # solver-type: "Parallel-Jacobi"
    constraint-type: "Stable-Neohookean-Combined"
    # constraint-type: "Stable-Neohookean"
    with-residual: false
    with-damping: false
    # residual-policy: "Every-Substep"
    residual-policy: "Never"

  -
    name: "Cube2"
    # type: "FirstOrderXPBDMeshObject"
    type: "XPBDMeshObject"
    # type: "FastFEMMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/tissue/Prostate.msh"
    # filename: "../resource/tissue/Trachea_processed.stl"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.4
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.125
    position: [-0.06125, 0.5, 10]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    collisions: false
    damping-multiplier: 20000
    solver-type: "Gauss-Seidel"
    # solver-type: "Jacobi"
    # solver-type: "Parallel-Jacobi"
    constraint-type: "Stable-Neohookean-Combined"
    # constraint-type: "Stable-Neohookean"
    with-residual: false
    with-damping: false
    # residual-policy: "Every-Substep"
    residual-policy: "Never"
  
  -
    name: "Cube3"
    # type: "FirstOrderXPBDMeshObject"
    type: "XPBDMeshObject"
    # type: "FastFEMMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/tissue/Prostate.msh"
    # filename: "../resource/tissue/Trachea_processed.stl"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.4
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.03125
    position: [-0.015625, 0.7, 10]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    collisions: false
    damping-multiplier: 20000
    solver-type: "Gauss-Seidel"
    # solver-type: "Jacobi"
    # solver-type: "Parallel-Jacobi"
    constraint-type: "Stable-Neohookean-Combined"
    # constraint-type: "Stable-Neohookean"
    with-residual: false
    with-damping: false
    # residual-policy: "Every-Substep"
    residual-policy: "Never"

  
  # -
  #   name: "Ground"
  #   type: "RigidMeshObject"
  #   primitive-type: "Plane"
  #   size: [0.1, 0.1, 0]
  #   position: [0, 0, 0]
  #   color: [1.0, 1.0, 1.0, 1.0]


