name: "blah"
visualization: "Easy3D"
g-accel: 9.81 # m/s2
sim-mode: "Frame-by-frame"
# sim-mode: "Visualization"
# sim-mode: "AFAP"
time-step: 1e-3
fps: 30
collision-rate: 1000 # Hz
end-time: 10
objects:

  -
    name: "Bottom"
    type: "XPBDMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.5
    position: [0, 0, 0.25]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-gamma: 2000
    collisions: true
    solver-type: "Gauss-Seidel"
    constraint-type: "Stable-Neohookean-Combined"
    with-residual: false
    with-damping: false
    # residual-policy: "Every-Substep"
    residual-policy: "Never"

  -
    name: "Top"
    type: "XPBDMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.5
    position: [0.0, 0, 0.8]
    velocity: [0, 0, -2]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-gamma: 2000
    collisions: true
    damping-multiplier: 25000
    solver-type: "Gauss-Seidel"
    constraint-type: "Stable-Neohookean-Combined"
    with-residual: false
    with-damping: false
    # residual-policy: "Every-Substep"
    residual-policy: "Never"


  
  -
    name: "Ground"
    type: "RigidMeshObject"
    primitive-type: "Plane"
    size: [1, 1, 0]
    position: [0, 0, 0]
    color: [1.0, 1.0, 1.0, 1.0]


