name: "Bunnies"
time-step: 5e-4
end-time: 10
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
    material:
      name: "Rubber"
      density: 1000
      E: 3e6
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 7
    position: [0, -7, 12]
    velocity: [0, 0, 1]

  - 
    name: "Cube2"
    type: "XPBDMeshObject"
    filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 1e6
      nu: 0.4999
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 7
    position: [0, 7, 12]
    velocity: [0, 0, 1]

  # -
  #   name: "Cube3"
  #   type: "XPBDMeshObject"
  #   filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
  #   material:
  #     name: "Steel"
  #     density: 7850
  #     E: 2e10
  #     nu: 0.25
  #   max-size: 3
  #   position: [0, 12, 5]
  #   velocity: [0, 0, 2]


