name: "blah"
g-accel: 9.81 # m/s2
sim-mode: "Visualization"
time-step: 1e-2
end-time: 5
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    filename: "../resource/cube.msh"
    material:
      name: "Rubber"
      density: 1000
      E: 3e6
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 5
    position: [0, -5, 10]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    solve-mode: "Sequential"

  - 
    # name: "Cube2"
    # type: "XPBDMeshObject"
    # filename: "../resource/refined_cube.msh"
    # material:
    #   name: "Rubber"
    #   density: 1000
    #   E: 3e6
    #   nu: 0.49
    # color: [1.0, 0.0, 0.0, 1.0]
    # draw-points: false
    # max-size: 5
    # position: [0, 5, 10]
    # velocity: [0, 0, 0]
    # rotation: [0, 30, 0]
    # num-solver-iters: 1
    # damping-stiffness: 100000
    # solve-mode: "Sequential"
  
  -
    name: "Ground"
    type: "RigidMeshObject"
    primitive-type: "Plane"
    size: [10, 20, 0]
    position: [0, 0, 0]
    color: [1.0, 1.0, 1.0, 1.0]


