name: "blah"
visualization: "Easy3D"
g-accel: 9.81 # m/s2
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"
time-step: 1e-3
collision-rate: 10100
fps: 30
end-time: 100
objects:

  -
    name: "Cube1"
    type: "FirstOrderXPBDMeshObject"
    # type: "XPBDMeshObject"
    # type: "FastFEMMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/cube/cube8.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/cube/cube32.msh"
    # filename: "../resource/tissue/Prostate.msh"
    # filename: "../resource/tissue/Trachea_processed.stl"
    # filename: "../resource/tissue/tracheal_tumor.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
      mu-s: 0.0
      mu-k: 0.0
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 1
    position: [0, 0, 1.2]
    velocity: [0, 0, 0.0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-gamma: 2000
    collisions: true
    damping-multiplier: 50000
    solver-type: "Gauss-Seidel"
    # solver-type: "Jacobi"
    # solver-type: "Parallel-Jacobi"
    constraint-type: "Stable-Neohookean-Combined"
    # constraint-type: "Stable-Neohookean"
    with-residual: false
    with-damping: false
    # residual-policy: "Every-Substep"
    residual-policy: "Never"
  
  # - 
  #   name: "ramp"
  #   type: "RigidBox"
  #   size: [5, 1, 0.2]
  #   density: 100000
  #   position: [0, 0, 0]
  #   rotation: [0, 0, 0]
  #   velocity: [0, 0, 0]
  #   angular-velocity: [0, 0, 0]
  #   fixed: true
  #   collisions: true

  -
    name: "sphere"
    type: "RigidSphere"
    radius: 0.5
    density: 10000
    position: [0, 0, 0]
    velocity: [0, 0, 0]
    fixed: true
    collisions: true

  # - name: "box2"
  #   type: "RigidBox"
  #   size: [0.1, 0.1, 0.1]
  #   position: [0, 0, 0]
  #   rotation: [10, 0, 0]
  #   velocity: [0, 5, 0]
  #   angular-velocity: [0, 0, 0]
  #   fixed: false
  #   collisions: true
  #   fixed: true


  # - name: "cylinder"
  #   type: "RigidCylinder"
  #   radius: 0.05
  #   height: 0.1
  #   density: 10000000
  #   position: [0, 0.2, 0.0]
  #   rotation: [100, 0, 0]
  #   velocity: [0, 0.1, 0]
  #   angular-velocity: [0, 0, 0]
  #   fixed: true
  #   collisions: true

  # - 
  #   name: "mesh_obj"
  #   type: "RigidMeshObject"
  #   filename: "../resource/general/stanford_bunny_lowpoly.stl"
  #   # filename: "../resource/cube/cube.obj"
  #   # sdf-filename: "../resource/sdf/stanford_bunny_lowpoly96.sdf"
  #   density: 100
  #   position: [0, 0, -2]
  #   rotation: [0, 27, 85]
  #   velocity: [0, 0, 0]
  #   angular-velocity: [0, 0, 0]
  #   max-size: 1
  #   collisions: true
  #   fixed: true

  # - name: "mesh_obj2"
  #   type: "RigidMeshObject"
  #   filename: "../resource/general/stanford_bunny_lowpoly.stl"
  #   # sdf-filename: "../resource/sdf/stanford_bunny_lowpoly.sdf"
  #   # filename: "../resource/cube/cube.obj"
  #   position: [0, 0, 0]
  #   rotation: [0, 0, 0]
  #   max-size: 1
  #   collisions: false
  #   color: [1, 0, 0, 0]

  

  # -
  #   name: "Cube2_res"
  #   # type: "FirstOrderXPBDMeshObject"
  #   type: "XPBDMeshObject"
  #   # type: "FastFEMMeshObject"
  #   # filename: "../resource/general/stanford_bunny_lowpoly.msh"
  #   # filename: "../resource/general/stanford_bunny_medpoly.msh"
  #   # filename: "../resource/general/single.msh"
  #   filename: "../resource/cube/cube8.msh"
  #   # filename: "../resource/cube/cube16.msh"
  #   # filename: "../resource/tissue/Prostate.msh"
  #   # filename: "../resource/tissue/Trachea_processed.stl"
  #   material:
  #     name: "Soft Tissue"
  #     density: 1000
  #     E: 6e4
  #     nu: 0.45
  #   color: [1.0, 0.5, 0.0, 1.0]
  #   draw-points: false
  #   draw-edges: true
  #   max-size: 0.5
  #   position: [0, 1, 0.25]
  #   velocity: [0, 0, 0]
  #   rotation: [0, 0, 0]
  #   num-solver-iters: 1
  #   damping-gamma: 2000
  #   collisions: false
  #   damping-multiplier: 25000
  #   solver-type: "Gauss-Seidel"
  #   constraint-type: "Stable-Neohookean-Combined"
  #   with-residual: true
  #   with-damping: false
  #   # residual-policy: "Every-Substep"
  #   residual-policy: "Never"


