name: "blah"
visualization: "Easy3D"
g-accel: 9.81 # m/s2
# sim-mode: "Frame-by-frame"
# sim-mode: "Visualization"
sim-mode: "AFAP"
time-step: 1e-3
fps: 30
end-time: 10
objects:
  # -
  #   name: "Trachea"
  #   # type: "FirstOrderXPBDMeshObject"
  #   type: "XPBDMeshObject"
  #   # type: "FastFEMMeshObject"
  #   # filename: "../resource/general/stanford_bunny_lowpoly.msh"
  #   # filename: "../resource/general/stanford_bunny_medpoly.msh"
  #   # filename: "../resource/general/single.msh"
    # filename: "../resource/cube/cube8.msh"
  #   # filename: "../resource/cube/cube16.msh"
  #   # filename: "../resource/tissue/Prostate.msh"
  #   # filename: "../resource/tissue/Trachea_processed.stl"
  #   # filename: "../resource/tissue/Trachea_processed_refined.stl"
  #   material:
  #     name: "Soft Tissue"
  #     density: 1000
  #     E: 6e4
  #     nu: 0.4
  #   color: [1.0, 0.5, 0.0, 1.0]
  #   draw-points: false
  #   draw-edges: false
  #   max-size: 0.1
  #   position: [0, 0, 1]
  #   velocity: [0, 0, 0]
  #   rotation: [0, 0, 0]
  #   num-solver-iters: 1
  #   damping-stiffness: 0
  #   collisions: false
  #   damping-multiplier: 20000
  #   solve-mode: "Simultaneous"

  -
    name: "Cube2"
    # type: "FirstOrderXPBDMeshObject"
    type: "XPBDMeshObject"
    # type: "FastFEMMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/tissue/Prostate.msh"
    # filename: "../resource/tissue/Trachea_processed.stl"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.5
    position: [0, 0, 0.25]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-gamma: 2000
    collisions: false
    damping-multiplier: 400000
    solver-type: "Gauss-Seidel"
    constraint-type: "Stable-Neohookean-Combined"
    with-residual: false
    with-damping: false
    residual-policy: "Never"
  
  -
    # name: "Cube3"
    # # type: "FirstOrderXPBDMeshObject"
    # type: "XPBDMeshObject"
    # # type: "FastFEMMeshObject"
    # # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # # filename: "../resource/general/stanford_bunny_medpoly.msh"
    # # filename: "../resource/general/single.msh"
    # filename: "../resource/cube/cube8.msh"
    # # filename: "../resource/cube/cube16.msh"
    # # filename: "../resource/tissue/Prostate.msh"
    # # filename: "../resource/tissue/Trachea_processed.stl"
    # material:
    #   name: "Soft Tissue"
    #   density: 1000
    #   E: 1e6
    #   nu: 0.4
    # color: [1.0, 0.5, 0.0, 1.0]
    # draw-points: false
    # draw-edges: true
    # max-size: 0.03125
    # position: [-0.015625, 0.7, 10]
    # velocity: [0, 0, 0]
    # rotation: [0, 0, 0]
    # num-solver-iters: 10
    # damping-stiffness: 0
    # collisions: false
    # damping-multiplier: 20000
    # solve-mode: "Simultaneous"

  
  -
    name: "Ground"
    type: "RigidMeshObject"
    primitive-type: "Plane"
    size: [1, 1, 0]
    position: [0, 0, 0]
    color: [1.0, 1.0, 1.0, 1.0]


