name: "blah"
g-accel: 9.81 # m/s2
# sim-mode: "Frame-by-frame"
sim-mode: "AFAP"
# sim-mode: "AFAP"
time-step: 1e-2
end-time: 200
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    filename: "../resource/beam/cube8.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 1
    position: [0, 1, 1]
    velocity: [0, 0, 0]
    rotation: [0, 0, 90]
    num-solver-iters: 1
    damping-stiffness: 0
    mass-to-damping-multiplier: 100
    residual-policy: "Never"
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    solve-mode: "First-Order-Simultaneous"
    # solve-mode: "Sequential-Init-Lambda"
    # solve-mode: "First-Order-Simultaneous"

  -
    name: "Cube2"
    type: "XPBDMeshObject"
    filename: "../resource/beam/cube8.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
    color: [1.0, 0.0, 0.0, 1.0]
    draw-points: false
    max-size: 1
    position: [0, -1, 0.5]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    mass-to-damping-multiplier: 100
    residual-policy: "Never"
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    # solve-mode: "Simultaneous"
    # solve-mode: "Sequential-Init-Lambda"
    solve-mode: "First-Order-Simultaneous"
  
  -
    name: "Ground"
    type: "RigidMeshObject"
    primitive-type: "Plane"
    size: [0.1, 0.5, 0]
    position: [0, 0, 0]
    color: [1.0, 1.0, 1.0, 1.0]


