name: "Bunnies"
time-step: 1e-2
end-time: 20
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
    material:
      name: "Rubber"
      density: 1000
      E: 3e6
      nu: 0.49
    max-size: 3
    position: [0, 0, 5]
    velocity: [0, 0, 2]

  # - 
  #   name: "Cube2"
  #   type: "XPBDMeshObject"
  #   filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
  #   material:
  #     name: "Soft Tissue"
  #     density: 1000
  #     E: 1e6
  #     nu: 0.4999
  #   max-size: 3
  #   position: [0, 6, 5]
  #   velocity: [0, 0, 2]
  
  -
    name: "Cube4"
    type: "XPBDMeshObject"
    filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
    material:
      name: "Rubber"
      density: 1000
      E: 3e6
      nu: 0.49
    max-size: 10
    position: [0, 10, 10]
    velocity: [0, 0, 2]
  # -
  #   name: "Cube3"
  #   type: "XPBDMeshObject"
  #   filename: "/home/smtobin/Documents/UTK/C++/XPBD/resource/refined_cube.msh"
  #   material:
  #     name: "Steel"
  #     density: 7850
  #     E: 2e10
  #     nu: 0.25
  #   max-size: 3
  #   position: [0, 12, 5]
  #   velocity: [0, 0, 2]


