name: "blah"
g-accel: 9.81 # m/s2
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"
time-step: 1e-2
fps: 30
end-time: 10
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    # type: "FastFEMMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    filename: "../resource/general/single.msh"
    # filename: "../resource/cube/cube8.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 1
    position: [0, 0.75, 1]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 20
    damping-stiffness: 0
    mass-to-damping-multiplier: 100
    g-scaling: 1
    residual-policy: "Every-Substep"
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    # solve-mode: "Simultaneous"
    # solve-mode: "Sequential-Init-Lambda"
    # solve-mode: "First-Order-Simultaneous"
    # solve-mode: "Sequential-g"
    solve-mode: "Simultaneous-g"
    # solve-mode: "Split-Deviatoric-Simultaneous9-g"
    # solve-mode: "Split-Deviatoric-Simultaneous10-g"

  -
    name: "Cube2"
    type: "XPBDMeshObject"
    # filename: "../resource/cube/cube8.msh"
    filename: "../resource/general/single.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.49
    color: [1.0, 0.0, 0.0, 1.0]
    draw-points: false
    max-size: 1
    position: [0, -0.75, 1]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 1
    damping-stiffness: 0
    mass-to-damping-multiplier: 10
    residual-policy: "Every-Substep"
    # solve-mode: "Split-Deviatoric-Sequential"
    # solve-mode: "Split-Deviatoric-Simultaneous9"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "Sequential"
    solve-mode: "Simultaneous"
    # solve-mode: "First-Order-Simultaneous"
    # solve-mode: "Sequential-Init-Lambda"
    # solve-mode: "First-Order-Simultaneous"
    # solve-mode: "Sequential-g"
    # solve-mode: "Simultaneous-g"
    # solve-mode: "Split-Deviatoric-Simultaneous9-g"
  
  -
    name: "Ground"
    type: "RigidMeshObject"
    primitive-type: "Plane"
    size: [0.75, 1.5, 0]
    position: [0, 0, 0]
    color: [1.0, 1.0, 1.0, 1.0]


