name: "blah"
g-accel: 9.81 # m/s2
# sim-mode: "Frame-by-frame"
sim-mode: "Visualization"
# sim-mode: "AFAP"
time-step: 1e-3
fps: 30
end-time: 50
objects:
  -
    name: "Cube1"
    type: "FirstOrderXPBDMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/tissue/Prostate.msh"
    material:
      name: "Soft Tissue"
      density: 100
      E: 6e4
      nu: 0.45
    color: [1.0, 0.5, 0.0, 1.0]
    draw-points: false
    max-size: 10
    position: [0, 0, 5]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 10
    mass-to-damping-multiplier: 1
    # residual-policy: "Every-Iteration"
    # solve-mode: "Sequential"
    solve-mode: "Simultaneous"
    # solve-mode: "Simultaneous-Jacobi"
    # solve-mode: "Simultaneous-Convergent-Jacobi"
  -
    name: "Cube2"
    type: "FirstOrderXPBDMeshObject"
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/tissue/Prostate.msh"
    material:
      name: "Soft Tissue"
      density: 100
      E: 6e4
      nu: 0.45
    color: [1.0, 0.0, 0.0, 1.0]
    draw-points: false
    max-size: 10
    position: [0, 12, 5]
    velocity: [0, 0, 0]
    rotation: [0, 0, 0]
    num-solver-iters: 10
    mass-to-damping-multiplier: 1
    # residual-policy: "Every-Iteration"
    solve-mode: "Sequential"
    # solve-mode: "Simultaneous"
    # solve-mode: "Simultaneous-Jacobi"
    # solve-mode: "Simultaneous-Convergent-Jacobi"

  
  # -
  #   name: "Ground"
  #   type: "RigidMeshObject"
  #   primitive-type: "Plane"
  #   size: [0.7, 0.7, 0]
  #   position: [0, 0, 0]
  #   color: [1.0, 1.0, 1.0, 1.0]


