name: "Virtuoso Trachea"
visualization: "VTK"

# Tissue grasping simulation-specific parameters
input-device: "Mouse" # the input device for interactivity - "Mouse" or "Haptic" (Phantom Omni)
fixed-faces-filename: "../resource/demos/trachea_virtuoso/trachea_fixed_faces.txt"
tumor-faces-filename: "../resource/demos/trachea_virtuoso/tumor_faces.txt"
# goal-filename: "../resource/demos/trachea_virtuoso/goals/goal1.obj"
# goals-folder: "../resource/demos/trachea_virtuoso/goals/"

# device-name1: "LeftOmni"
# device-name2: "RightOmni"
# device-name1: "Omni"
g-accel: 0 # m/s2
# sim-mode: "Visualization"
# sim-mode: "Frame-by-frame"
sim-mode: "AFAP"
time-step: 3.33e-3 # for FO XPBD
# time-step: 3.33e-5 # for normal XPBD
collision-rate: 1000
fps: 30
end-time: 10000
objects:

  -
    name: "Cube1"
    # type: "XPBDMeshObject"
    type: "FirstOrderXPBDMeshObject"
    # filename: "../resource/cube/cube8.msh"
    filename: "../resource/demos/trachea_virtuoso/trachea_with_tumor.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.49
    max-size: 0.06
    position: [0, 0, 0]
    velocity: [0, 0, 0]
    rotation: [0, 180, 0]
    num-solver-iters: 1
    residual-policy: "Never"
    solver-type: "Gauss-Seidel"
    constraint-type: "Stable-Neohookean-Combined"
    with-residual: false
    with-damping: false
    # damping-multiplier: 400000000
    damping-multiplier: 600000000
    collisions: true
    
    color: [1.0, 0.3, 0.2]
    render-type: "PBR"
    metallic: 0.05
    roughness: 0.4
    draw-points: false
    draw-edges: true

  -
    name: "Robot"
    type: "VirtuosoRobot"
    position: [0, -0.03, -0.0015]
    rotation: [-90, 180, 0]

    color: [0.7, 0.7, 0.7]
    render-type: "PBR"
    metallic: 1.0
    roughness: 0.4
    arms:
    -
      name: "Arm1"
      type: "VirtuosoArm"
      outer-tube-diameter: 1.56e-3
      outer-tube-radius-of-curvature: 1.5383e-2
      outer-tube-distal-straight-length: 5e-3
      outer-tube-translation: 7e-3
      outer-tube-rotation: 30
      inner-tube-rotation: 30
      inner-tube-diameter: 1.04e-3
      inner-tube-translation: 20e-3
      collisions: false

      color: [0.7, 0.7, 0.7]
      render-type: "PBR"
      metallic: 1.0
      roughness: 0.4

    -
      name: "Arm2"
      type: "VirtuosoArm"
      outer-tube-diameter: 1.56e-3
      outer-tube-radius-of-curvature: 1.5383e-2
      outer-tube-distal-straight-length: 5e-3
      outer-tube-translation: 7e-3
      outer-tube-rotation: -45
      inner-tube-rotation: 45
      inner-tube-diameter: 1.04e-3
      inner-tube-translation: 20e-3
      collisions: false

      color: [0.7, 0.7, 0.7]
      render-type: "PBR"
      metallic: 1.0
      roughness: 0.4

  


