name: "Virtuoso Trachea"

# Tissue grasping simulation-specific parameters
input-device: "Mouse" # the input device for interactivity - "Mouse" or "Haptic" (Phantom Omni)
fixed-faces-filename: "../resource/demos/trachea_virtuoso/trachea_fixed_faces.txt"
tumor-faces-filename: "../resource/demos/trachea_virtuoso/tumor_faces.txt"
# goal-filename: "../resource/demos/trachea_virtuoso/goals/goal1.obj"
goals-folder: "../resource/demos/trachea_virtuoso/goals/"

# fixed-faces-filename: "../resource/demos/trachea_virtuoso/tracheal_tumor_v2_refined_fixed_faces.txt"
# tumor-faces-filename: "../resource/demos/trachea_virtuoso/tracheal_tumor_v2_refined_tumor_faces.txt"

# device-name1: "LeftOmni"
# device-name2: "RightOmni"
# device-name1: "Omni"

g-accel: 0 # m/s2
# sim-mode: "Visualization"
# sim-mode: "Frame-by-frame"
sim-mode: "AFAP"
time-step: 3.33e-3 # for FO XPBD
# time-step: 3.33e-5 # for normal XPBD
collision-rate: 1000
fps: 30
end-time: 5000
objects:

  -
    name: "Cube1"
    # type: "XPBDMeshObject"
    type: "FirstOrderXPBDMeshObject"
    # filename: "../resource/cube/cube8.msh"
    filename: "../resource/demos/trachea_virtuoso/trachea_with_tumor.msh"
    # filename: "../resource/demos/trachea_virtuoso/tracheal_tumor_v2_refined.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e5
      nu: 0.49
    color: [1.0, 0.3, 0.2, 1.0]
    draw-points: false
    draw-edges: true
    max-size: 0.06
    position: [0,-0.03, 0]
    velocity: [0, 0, 0]
    rotation: [0, 180, 0]
    num-solver-iters: 1
    residual-policy: "Never"
    solver-type: "Gauss-Seidel"
    # solver-type: "Jacobi"
    # solver-type: "Parallel-Jacobi"
    constraint-type: "Stable-Neohookean-Combined"
    with-residual: false
    with-damping: false
    damping-multiplier: 4000000000
    # damping-multiplier: 20000000000
    collisions: true
    draw-faces: true
    draw-points: true
    draw-edges: false

  -
    name: "Robot"
    type: "VirtuosoRobot"
    position: [0, -0.06, -0.0015]
    rotation: [-90, 180, 0]
    collisions: true
    arms:
    -
      name: "Arm1"
      type: "VirtuosoArm"
      outer-tube-diameter: 1.56e-3
      outer-tube-radius-of-curvature: 1.5383e-2
      outer-tube-distal-straight-length: 5e-3
      outer-tube-translation: 7e-3
      outer-tube-rotation: 30
      inner-tube-rotation: 30
      inner-tube-diameter: 1.04e-3
      inner-tube-translation: 20e-3

    # -
    #   name: "Arm2"
    #   type: "VirtuosoArm"
    #   outer-tube-diameter: 1.56e-3
    #   outer-tube-radius-of-curvature: 1.5383e-2
    #   outer-tube-distal-straight-length: 5e-3
    #   outer-tube-translation: 7e-3
    #   outer-tube-rotation: -45
    #   inner-tube-rotation: 45
    #   inner-tube-diameter: 1.04e-3
    #   inner-tube-translation: 20e-3

  


