name: "cantilevered_flesh_cube"
output-folder: "../output/cantilever_beam"
g-accel: 9.81 # m/s2
# sim-mode: "AFAP"
sim-mode: "Visualization"
time-step: 1e-3
end-time: 100
objects:
  -
    name: "Cube1"
    type: "XPBDMeshObject"
    filename: "../resource/cube/cube8.msh"
    material:
      name: "Macklin"
      density: 1000
      E: 6e4
      nu: 0.49
    color: [1.0, 0.509, 0.0, 1.0]
    draw-points: false
    max-size: 0.5
    position: [0, 0, 1]
    damping-stiffness: 0
    num-solver-iters: 1
    mass-to-damping-multiplier: 200
    residual-policy: "Never"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    # solve-mode: "First-Order-Simultaneous"
    solve-mode: "Simultaneous"

  -
    name: "Cube2"
    type: "XPBDMeshObject"
    filename: "../resource/cube/cube8.msh"
    material:
      name: "Soft Tissue"
      density: 1000
      E: 6e4
      nu: 0.45
    color: [1.0, 0.0, 0.0, 1.0]
    draw-points: false
    max-size: 0.5
    position: [0, 0, 1.8]
    damping-stiffness: 0
    num-solver-iters: 1
    residual-policy: "Never"
    # solve-mode: "Split-Deviatoric-Simultaneous10"
    solve-mode: "Simultaneous"


