#!/usr/bin/env python3
"""
自动给OBJ文件添加UV坐标（推荐：Spherical UV 适合 tumor）并做“重复纹理”的 wrap：
    uv = (uv * repeat) % 1.0

用法:
  python3 ./scripts/add_uv_to_obj.py input.obj output.obj
可选参数:
  --repeat_u 10 --repeat_v 10
  --center_mode mean|bbox   (默认 mean)
说明:
- 输出面索引为 v/vt（不写 vn），避免原OBJ法线索引与顶点数不一致导致错误。
- 如果你在C++里需要法线，建议在加载后自己重算（per-vertex normal）。
"""

import sys
import numpy as np


def parse_args(argv):
    repeat_u = 10.0
    repeat_v = 10.0
    center_mode = "mean"  # "mean" or "bbox"

    i = 0
    while i < len(argv):
        if argv[i] == "--repeat_u" and i + 1 < len(argv):
            repeat_u = float(argv[i + 1])
            i += 2
        elif argv[i] == "--repeat_v" and i + 1 < len(argv):
            repeat_v = float(argv[i + 1])
            i += 2
        elif argv[i] == "--center_mode" and i + 1 < len(argv):
            center_mode = argv[i + 1].strip().lower()
            if center_mode not in ("mean", "bbox"):
                raise ValueError("--center_mode must be 'mean' or 'bbox'")
            i += 2
        else:
            i += 1

    return repeat_u, repeat_v, center_mode


def read_obj_vertices_faces(input_obj):
    vertices = []
    faces = []

    with open(input_obj, "r") as f:
        for line in f:
            if line.startswith("v "):
                parts = line.strip().split()
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif line.startswith("f "):
                parts = line.strip().split()[1:]
                face = []
                for p in parts:
                    # supports: v, v/vt, v/vt/vn, v//vn
                    v_idx = int(p.split("/")[0])
                    face.append(v_idx)
                faces.append(face)

    return np.asarray(vertices, dtype=np.float64), faces


def compute_center(vertices, mode="mean"):
    if mode == "mean":
        return vertices.mean(axis=0)
    # bbox center
    vmin = vertices.min(axis=0)
    vmax = vertices.max(axis=0)
    return (vmin + vmax) * 0.5


def add_spherical_uv(vertices, repeat_u=10.0, repeat_v=10.0, center_mode="mean"):
    """
    Spherical UV:
      p = v - center
      u = atan2(p.y, p.x)/(2π) + 0.5
      v = acos(p.z/||p||)/π
    then repeat+wrap:
      u = (u * repeat_u) % 1
      v = (v * repeat_v) % 1
    """
    center = compute_center(vertices, mode=center_mode)
    p = vertices - center

    r = np.linalg.norm(p, axis=1)
    r = np.where(r < 1e-12, 1e-12, r)

    angles = np.arctan2(p[:, 1], p[:, 0])
    u = (angles + np.pi) / (2.0 * np.pi)  # [0,1)

    cos_theta = np.clip(p[:, 2] / r, -1.0, 1.0)
    v_coord = np.arccos(cos_theta) / np.pi  # [0,1]

    # repeat + wrap
    u = (u * repeat_u) % 1.0
    v_coord = (v_coord * repeat_v) % 1.0

    return np.stack([u, v_coord], axis=1), center


def write_obj_with_uv(output_obj, vertices, uvs, faces, meta_comment=""):
    with open(output_obj, "w") as f:
        f.write("# OBJ with UV coordinates\n")
        f.write("# Generated by add_uv_to_obj.py\n")
        if meta_comment:
            f.write(f"# {meta_comment}\n")
        f.write("\n")

        # vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")

        # uvs
        for uv in uvs:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        f.write("\n")

        # faces: v/vt (1-based indices)
        for face in faces:
            f.write("f " + " ".join([f"{vi}/{vi}" for vi in face]) + "\n")


def main():
    if len(sys.argv) < 3:
        print("用法: python3 add_uv_to_obj.py <输入.obj> <输出.obj> [--repeat_u N] [--repeat_v N] [--center_mode mean|bbox]")
        print("示例: python3 add_uv_to_obj.py tumor.obj tumor_uv.obj --repeat_u 10 --repeat_v 10 --center_mode mean")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]
    repeat_u, repeat_v, center_mode = parse_args(sys.argv[3:])

    print(f"📖 读取文件: {input_file}")
    vertices, faces = read_obj_vertices_faces(input_file)
    print(f"✅ 找到 {len(vertices)} 个顶点, {len(faces)} 个面")

    print("🎨 生成UV坐标（spherical）...")
    uvs, center = add_spherical_uv(vertices, repeat_u=repeat_u, repeat_v=repeat_v, center_mode=center_mode)

    print(f"✅ 生成了 {len(uvs)} 个UV坐标")
    print(f"   repeat_u={repeat_u}, repeat_v={repeat_v}, wrap=mod1")
    print(f"   center_mode={center_mode}, center=({center[0]:.4f}, {center[1]:.4f}, {center[2]:.4f})")

    meta = f"spherical_uv repeat_u={repeat_u} repeat_v={repeat_v} center_mode={center_mode}"
    print(f"💾 保存文件: {output_file}")
    write_obj_with_uv(output_file, vertices, uvs, faces, meta_comment=meta)

    print("✅ 完成！")
    print("\n📊 UV坐标范围:")
    print(f"   U: {uvs[:, 0].min():.3f} ~ {uvs[:, 0].max():.3f}")
    print(f"   V: {uvs[:, 1].min():.3f} ~ {uvs[:, 1].max():.3f}")


if __name__ == "__main__":
    main()
