#!/usr/bin/env python3
"""
自动给OBJ文件添加UV坐标
用法: python3 add_uv_to_obj.py input.obj output.obj
"""

import sys
import numpy as np

def add_cylindrical_uv(input_obj, output_obj):
    """
    读取OBJ文件，添加圆柱形UV坐标，保存新文件
    """
    print(f"📖 读取文件: {input_obj}")
    
    vertices = []
    faces = []
    normals = []
    
    # 读取OBJ
    with open(input_obj, 'r') as f:
        for line in f:
            if line.startswith('v '):
                parts = line.strip().split()
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif line.startswith('vn '):
                parts = line.strip().split()
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif line.startswith('f '):
                # 只提取顶点索引
                parts = line.strip().split()[1:]
                face = []
                for p in parts:
                    # 处理 v, v/vt, v/vt/vn, v//vn 格式
                    vertex_idx = int(p.split('/')[0])
                    face.append(vertex_idx)
                faces.append(face)
    
    vertices = np.array(vertices)
    print(f"✅ 找到 {len(vertices)} 个顶点, {len(faces)} 个面")
    
    # 生成圆柱形UV坐标
    print("🎨 生成UV坐标...")
    z_min = vertices[:, 2].min()
    z_max = vertices[:, 2].max()
    z_range = z_max - z_min if z_max > z_min else 1.0
    
    uvs = []
    for v in vertices:
        x, y, z = v
        
        # U: 绕Z轴的角度
        angle = np.arctan2(y, x)
        u = (angle + np.pi) / (2 * np.pi)
        
        # V: Z轴位置
        v_coord = (z - z_min) / z_range
        
        uvs.append([u, v_coord])
    
    uvs = np.array(uvs)
    print(f"✅ 生成了 {len(uvs)} 个UV坐标")
    
    # 写入新OBJ
    print(f"💾 保存文件: {output_obj}")
    with open(output_obj, 'w') as f:
        f.write("# OBJ with UV coordinates\n")
        f.write("# Generated by add_uv_to_obj.py\n\n")
        
        # 写入顶点
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")
        
        # 写入UV
        for uv in uvs:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        f.write("\n")
        
        # 写入法线（如果有）
        if normals:
            for n in normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
            f.write("\n")
        
        # 写入面（带UV索引）
        for face in faces:
            if normals:
                # 格式: v/vt/vn
                f.write("f " + " ".join([f"{v}/{v}/{v}" for v in face]) + "\n")
            else:
                # 格式: v/vt
                f.write("f " + " ".join([f"{v}/{v}" for v in face]) + "\n")
    
    print("✅ 完成！")
    print(f"\n📊 UV坐标范围:")
    print(f"   U: {uvs[:, 0].min():.3f} ~ {uvs[:, 0].max():.3f}")
    print(f"   V: {uvs[:, 1].min():.3f} ~ {uvs[:, 1].max():.3f}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("用法: python3 add_uv_to_obj.py <输入.obj> <输出.obj>")
        print("\n示例:")
        print("  python3 add_uv_to_obj.py tbone_ds06.obj tbone_ds06_with_uv.obj")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    add_cylindrical_uv(input_file, output_file)
